name: zhihu
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # 开发工具
  page_route_animator: ^1.0.4 # 页面过渡动画
  flutter_inappwebview: ^6.0.0 # webview
  cached_network_image: ^3.4.1 # 图片缓存
  flutter_screenutil: ^5.9.3 # 屏幕适配
  flutter_smart_dialog: ^4.9.8+5 # 弹窗
  url_launcher: ^6.3.0 # url跳转
  easy_refresh: ^3.3.2+1 # 刷新
  dynamic_color: any # 动态取色
  share_plus: ^10.1.2 # 分享
  go_router: ^14.4.1 # 路由
  intl: ^0.19.0 # 国际化

  # 界面组件
  loading_animation_widget: ^1.2.1 # 加载动画
  auto_size_text: ^3.0.0 # 文本自适应
  gap: ^3.0.1 # 间隔

  # 状态管理
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1

  # 本地数据库
  floor: ^1.5.0
#  hive: ^2.2.3

  # 网络请求
  dio: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.1 # 应用图标生成

  build_runner: ^2.4.12
  floor_generator: ^1.5.0
  riverpod_generator: ^2.6.1

  custom_lint: ^0.6.8
  riverpod_lint: ^2.6.1

# 应用图标生成
flutter_launcher_icons:
  android: "launcher_icon"
  min_sdk_android: 21
  ios: true
  image_path: "assets/images/icon/daily.zhihu-1024x1024.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/macos_3840x2160.jpg
    - assets/images/icon/daily.zhihu-1024x1024.png
    - assets/images/png/ConneR.png

